### PR TITLE
Adapt to new plugin loader  at 

### PR DESCRIPTION
**Pull request by leamas**
Some cleanup + fixes to make it work with the new plugin loader at https://github.com/OpenCPN/OpenCPN/pull/1390.

This plugin represents the simplest case when adapting a plugin with just a library file. See https://github.com/leamas/oesenc_pi/ to get a roadmap for the changes.

Uploading to bintray will fail when merged since your repo requires a new key. Please let me know if you want to fix this. It will require some private messaging to transfer the API key. Besides this, the builds should work

### CODE REVIEW

**Comment by rgleason** [comment]
Leamas, very big surprise to get the PR.

The most recent commit failed and for some reason my Norton 360 security called it a problem and appveyor a suspicious website and I had to make a user report (favorable) and say I was continuing to use it.  https://ci.appveyor.com/project/rgleason/bsb4-pi/builds/26837481
Here is the notice on appveyor - It was in red:
```
[1/2] build\bsb4-plugin-msvc-10.0.14393.xml (907 bytes)...100%
[2/2] build\bsb4_pi-1.5.0-1_msvc-10.0.14393.tar.gz (71,359 bytes)...100%
Deploying using BinTray provider
Provider setting not found or it's value is empty. If secure setting is used please check that value was encrypted (or YAML was exported) while being logged under correct account.
Parameter name: api_key
```
The previous PR compiled and built and left files.
See Appveyor history.
https://ci.appveyor.com/project/rgleason/bsb4-pi/history

Do I need to do something with an appveyor auth key?  (I am not pushing thesee to release now.)

Also what version of O runs with these? Should I try it?  I don't have bsb4 charts though. I can see how it installls/uninstalls though.

Is this a decent roadmap for adapting plugins or should I look at a more complex successfully changed plugin ?

**Comment by leamas** [comment]
> Do I need to do something with an appveyor auth key? (I am not pushing thesee to release now.)

Probably, yes. The whole idea is that you and appveyor share a secret. The best you could do is probably to follow https://www.appveyor.com/docs/deployment/bintray/  and https://www.appveyor.com/docs/how-to/secure-files/  to use your own data

> Also what version of O runs with these? Should I try it? I don't have bsb4 charts though. I can see how it installls/uninstalls though.

The setup.exe should work with standard O5.

The tarball  only works with the new plugin loader. Also, to actually use it you must 

   - Upload it somewhere out there.
   - Update the xml file so the url points to "your" version.
   - Update ocpn-plugins.xml with the xml file, see plugins/README.md in https://github.com/OpenCPN/OpenCPN/pull/1390

If you have time to try the plugin, both the tarball and the standard setup package I would be really interested in the results.

> Is this a decent roadmap for adapting plugins or should I look at a more complex successfully changed plugin ?

Sort of. It describes the minimal changes required for a plugin with just a dll/so file. So it should be a good starter, but if you want to adapt a plugin with data files you should also take a look at https://github.com/leamas/radar_pi as well.

If you have a plugin with helper binaries and extra libs: choose another plugin for now ;)

**Comment by rgleason** [comment]
Leamas, 
Norton 360 is becoming a PITA again. It is labeling as Malicious, appveyor directories that have  appveyor encrypted github auth_tokens too!!!  It is pretty dumb I think.
However your point is taken, I will try to auth_token all the rest even though it is protected by PW. Big job though.

I will try both exe and tarball installed into standard O5. May take a few days. Thanks for all of your great work. It is looking better and better from hear.

BTW Leamas, How's the boat work at this point?

**Comment by leamas** [comment]
> I will try both exe and tarball installed into standard O5

The tarball will certainly not work with standard 05, only with  the PR with the new plugin loader :)

**Pull request merged**
